[package]
name = "swc_plugin_add_import_extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
swc_ecma_transforms_testing = "*"

[dependencies]
once_cell = "1"
regex = "1"
serde = "1"
swc_ecma_parser = "*"
swc_plugin = "*"
tracing = "*"