name: Publish

permissions:
  contents: read

on:
  push:
    tags:
      - v*
    branches:
      - publish-test

jobs:
  publish-npm:
    name: Publish on npm
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install rustup `stable` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
          override: true

      - name: Setup node.js with NPM registry
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm & deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Use rust cache action
        uses: Swatinem/rust-cache@v2

      - name: Run pnpm publish
        run: pnpm publish --dry-run --publish-branch=publish-test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    name: Publish on github packages
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install rustup `stable` toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi
          override: true

      - name: Setup node.js with github packages registry
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install pnpm & deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Use rust cache action
        uses: Swatinem/rust-cache@v2

      - name: Run pnpm publish
        run: pnpm publish --dry-run --publish-branch=publish-test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com'
